---

variables:
  GIT_DEPTH: 1

stages:
- quality
- sast
- sast-format

sast:
  stage: sast
  tags: [docker]
  artifacts:
    paths: [gl-sast-report.json]

format-json:
  allow_failure: true
  stage: sast-format
  tags: [docker]
  image: python
  script:
    - ls
    - python -m json.tool gl-sast-report.json > pretty-sast-report.json
  artifacts:
    paths:
      - pretty-sast-report.json

flake8:
  allow_failure: true
  stage: quality
  tags: [docker]
  image: python
  before_script:
    - python -m pip install flake8
  script:
    - flake8 --max-line-length=120 ./reporter.py

commisery:
  stage: quality
  allow_failure: true
  tags: [docker]
  image: python
  before_script:
    - apt-get update && apt-get -y install git
    - git clone https://github.com/tomtom-international/commisery.git
    - cd commisery
    - pip install .
  script:
    - commit=$(git rev-parse --short HEAD)
    - cm check $commit

include:
  - template: Jobs/SAST.gitlab-ci.yml
