name: Quality pipeline

on: [push]

jobs:
    actionlint:
        name: Actionlint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Check workflow files
              uses: docker://rhysd/actionlint:latest
    flake:
        runs-on: ubuntu-latest
        name: Flake8
        steps:
            - name: Check out source repository
              uses: actions/checkout@v4
            - name: Set up Python environment
              uses: actions/setup-python@v5
              with:
                python-version: "3.11"
            - name: flake8 Lint
              uses: py-actions/flake8@v2
              with:
                max-line-length: "150"
    commisery:
        runs-on: ubuntu-latest
        name: Commisery
        permissions: read-all
        steps:
            - name: Check for Conventional Commit compliance
              uses: tomtom-international/commisery-action@v2
              with:
                token: ${{ github.token }}